[workspace]
resolver = "2"
members = ["program"]

[workspace.metadata.cli]
solana = "2.1.14"

# Specify Rust toolchains for rustfmt, clippy, and build.
# Any unprovided toolchains default to stable.
[workspace.metadata.toolchains]
format = "1.84.1"
lint = "1.84.1"
